### PR TITLE
Added Url attribute to graph elements

### PR DESCRIPTION
**Pull request by ianakotey**
## Additions
 This pull request adds the url attribute to the graph, subgraph, node and edge structs. 

## Testing
It also adds tests to ensure that no code is broken. Tests can be found in the integration.rs file.

## Other changes
Rustfmt was used to format repository before pull request was made.

### CODE REVIEW

**Comment by SelamaAshalanore** [comment]
Hi, thanks a lot for the effort! I'd love to merge this PR. Although, you might want to separate the format part for another PR to keep this PR focused only on the URL attribute.

**Comment by ianakotey** [comment]
Hello, I'll make the changes and let you know

**Comment by ianakotey** [comment]
I've reverted the format commit. In hindsight, it was not the best idea. Thanks for pointing it out

**Comment by SelamaAshalanore** [comment]
Well written! Thanks for your contribution.

**Pull request merged**
